### PR TITLE
Fixed queries not executing until the next sleeper wakeup

### LINKED ISSUE #90: Calling libasynql functions won't execute until we call another one.
**Describe the bug**
When you call any libasynql function, let's say `executeSelect`, the `onSelect` function will never executed until another libasynql function called. and the second libasynql function well never get it's results until another function is called...

Something I noticed is that the bug does not exist in older versions. (before [DEV-182](https://poggit.pmmp.io/ci/poggit/libasynql/libasynql/dev:182) https://github.com/poggit/libasynql/commit/f0d668c9699824bb8d2433421c2401d385099a45)

**Sample code**
https://github.com/Aboshxm2/libasyncql_query_bug

sqlite.sql
```sql
-- #!sqlite
-- #{ libasyncql_query_bug.init
CREATE TABLE IF NOT EXISTS example_table (playerName TEXT PRIMARY KEY, kills INTEGER);
-- #}
-- #{ libasyncql_query_bug.select
-- # :playerName string
SELECT * FROM example_table WHERE playerName=:playerName;
-- #}
-- #{ libasyncql_query_bug.insert
-- # :playerName string
-- # :kills int
INSERT INTO example_table (playerName, kills) VALUES (:playerName, :kills)
-- #}
```
Main.php
```php
    private DataConnector $database;

    protected function onEnable(): void
    {
        $this->database = libasynql::create($this, [
            "type" => "sqlite",
            "sqlite" => ["file" => "data.sqlite"],
            "worker-limit" => 1
        ], [
            "sqlite" => "sqlite.sql"
        ]);

        $this->database->executeGeneric("libasyncql_query_bug.init", [], null, function (SqlError $error): void {
            throw new $error;
        });
    }

    public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool
    {
        if(!isset($args[0])) {
            $sender->sendMessage("/test (insert|select)");
            return true;
        }

        if($args[0] === "insert") {

            if(count($args) < 3) {
                $sender->sendMessage("/test insert (playerName) (kills)");
                return true;
            }

            $this->database->executeInsert("libasyncql_query_bug.insert", ["playerName" => $args[1], "kills" => (int)$args[2]], function (int $_) {
                var_dump("insert query executed successfully.");
            }, function (SqlError $error): void {
                throw new $error;
            });

        }elseif($args[0] === "select") {

            if(count($args) < 2) {
                $sender->sendMessage("/test select (playerName)");
                return true;
            }

            $this->database->executeSelect("libasyncql_query_bug.select", ["playerName" => $args[1]], function (array $rows) {
                var_dump("select query executed successfully.");
                var_dump($rows);
            }, function (SqlError $error): void {
                throw new $error;
            });
        }
```

**Expected behavior**
When I do `/test insert player1 10`, It should display "insert query executed successfully." in the console.
but it doesn't. until I send another command `/test insert player2 10`

**Tests**
1: `/test insert player1 10`. 
resaults: 
nothing.

2: `/test insert player1 10` then `/test select player1`. 
resaults: 
```
"insert query executed successfully.".
```

3: `/test insert player1 10` then `/test select player1` then `/test select player2`
resaults: 
```
"insert query executed successfully."`
"select query executed successfully."
array(1) {
  [0]=>
  array(2) {
    ["playerName"]=>
    string(2) "player1"
    ["kills"]=>
    int(1)
  }
}
```

4: `/test insert player1 10` then `/test select player2` then `/test select player1`
resaults: 
```
"insert query executed successfully."`
"select query executed successfully."
array(0) {
}

```

**Environment**
OS: linux
PocketMine version: 4.12.2
PHP version: 8.0.17

I am sorry if there any misspelling. English is not my main language.

### PR DESCRIPTION
**Pull request by JavierLeon9966**
Apparently `Threaded->count()` and `Threaded->shift()` are not synchronized with each other and that was the cause of the issue.
Fixes #90

### CODE REVIEW

**Comment by dktapps** [comment]
~~That doesn't make any sense.~~ Never mind, I see the problem.

File: libasynql/src/poggit/libasynql/base/QueryRecvQueue.php [hunk 1]
```diff
@@ -50,10 +50,12 @@ public function publishError(int $queryId, SqlError $error) : void{
 	}
 
 	public function fetchResults(&$queryId, &$results) : bool{
-		$row = $this->shift();
-		if(is_string($row)){
-			[$queryId, $results] = unserialize($row, ["allowed_classes" => true]);
-			return true;
+		while($this->count() > 0){
+			$row = $this->shift();
```
Comment (dktapps) [inline libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: You can replace this with a `while(($row = $this->shift()) !== null)` or `while(is_string($row = $this->shift()))` to avoid the extra call (and extra lock/unlock).

Comment (JavierLeon9966) [reply libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: I think you mean `while(($row = $this->shift()) === null)` because `shift()` will return `null` until it synchronizes, and we're waiting until it does

Comment (dktapps) [reply libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: No. It only returns null if the buffer is empty (i.e. count == 0).

File: libasynql/src/poggit/libasynql/base/QueryRecvQueue.php [hunk 2]
```diff
@@ -50,12 +50,10 @@ public function publishError(int $queryId, SqlError $error) : void{
 	}
 
 	public function fetchResults(&$queryId, &$results) : bool{
-		while($this->count() > 0){
-			$row = $this->shift();
-			if(is_string($row)){
-				[$queryId, $results] = unserialize($row, ["allowed_classes" => true]);
-				return true;
-			}
+		if($this->count() > 0){
```
Comment (SOF3) [inline libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: why can't you just change this to `while(($row = $this->shift()) !== null` here? Why do you need to check for the count?

File: libasynql/src/poggit/libasynql/base/QueryRecvQueue.php (hunk 1 above)
Comment (JavierLeon9966) [reply libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: But the problem here is that `Threaded->count()` will tell us that the buffer isn't empty, but when we do `Threaded->shift()` after that it will return `null` until later. If I do `Threaded->shift()` first the problem will be the same because it will return `null` on waking up from the sleeper and checking we got something in the buffer:
https://github.com/poggit/libasynql/blob/4df7dc2b44de0b6f5cb401dee90c8395655b3ebc/libasynql/src/poggit/libasynql/base/QueryRecvQueue.php#L66

File: libasynql/src/poggit/libasynql/base/QueryRecvQueue.php [hunk 3]
```diff
@@ -50,12 +50,12 @@ public function publishError(int $queryId, SqlError $error) : void{
 	}
 
 	public function fetchResults(&$queryId, &$results) : bool{
-		if($this->count() > 0){
-			while(($row = $this->shift()) === null);
-			[$queryId, $results] = unserialize($row, ["allowed_classes" => true]);
-			return true;
+		while(is_int($row = $this->shift())); //Somehow $this->availableThreads are here, so we have to remove them. TODO: Remove available threads in the next major update.
```
Comment (dktapps) [inline libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: You might as well remove it directly, it's not going to do what you want anyway.

Comment (JavierLeon9966) [reply libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: Hmm, I guess I'll deprecate the methods then.

Comment (dktapps) [reply libasynql/src/poggit/libasynql/base/QueryRecvQueue.php]: Seems to me like they are internal methods, no one should be using them.

**Review by dktapps — APPROVED** [review]
