### PR TITLE
Use pmmp/Snooze instead of bare-usleeping

### LINKED ISSUE #15: Threaded::wait() isn't called in synchronized()
Not gonna fix this directly; migrating to pmmp/Snooze instead.

### LINKED ISSUE #22: High CPU on Linux hosts only.
**Describe the bug**
Servers running Linux have High CPU usage when a server containing this is running.

**Expected behavior**
CPU to stay at a lower level than what the allocated CPU is for the instances.

**Other Info** 
Me and matcracker looked into this issue on his plugin BedCoreProtect and found that the viron only affects Linux hosts.

**Environment**
OS: Linux Ubuntu 16.04, 18.04, 19.04 CentOS 7
PocketMine versions: 3.0.0 - 3.11.1

### PR DESCRIPTION
**Pull request by CortexPE**
Close #15
Close #22

This change also makes it so that mysqli connections are not pinged every 5 minutes, but only if the connection is dead before a query.

Some code refactoring might be needed in the future, but this contribution aims to be as less invasive / destructive as possible.

tnx @dktapps

### CODE REVIEW

**Comment by ImCatelyn** [comment]
wut this

**Comment by lambuui** [comment]
wut this, hurting me brain lol

**Comment by dktapps** [comment]
if you don't have something of value to add to the PR discussion, please don't bother to comment

File: libasynql/src/poggit/libasynql/DataConnector.php [hunk 1]
```diff
@@ -120,6 +120,13 @@ public function executeSelectRaw(string $query, array $args = [], ?callable $onS
 	 */
 	public function waitAll() : void;
 
+	/**
+	 * This function checks for the results of the queries handled before it was called. and proceeds to run them... check any implementation of SqlThread->readResults()
+	 *
+	 * @internal
```
Comment (SOF3) [inline libasynql/src/poggit/libasynql/DataConnector.php]: If it is an internal method, it shouldn't be in this interface.
Internals can always take a DataConnectorImpl directly. The interface is only intended for dependency injection in the userland.

File: libasynql/src/poggit/libasynql/base/SqlThreadPool.php [hunk 2]
```diff
@@ -38,22 +43,41 @@ class SqlThreadPool implements SqlThread{
 	/** @var QueryRecvQueue */
 	private $bufferRecv;
 
+	/** @var DataConnector|null */
+	private $dataConnector = null;
+
+	/**
+	 * @param DataConnector $dataConnector
+	 */
+	public function setDataConnector(DataConnector $dataConnector): void {
```
Comment (SOF3) [inline libasynql/src/poggit/libasynql/base/SqlThreadPool.php]: You could directly make this take a DataConnectorImpl.

File: libasynql/src/poggit/libasynql/base/SqlThreadPool.php [hunk 3]
```diff
@@ -38,22 +43,41 @@ class SqlThreadPool implements SqlThread{
...
+		});
+
 		$this->workerFactory = $workerFactory;
 		$this->workerLimit = $workerLimit;
 		$this->bufferSend = new QuerySendQueue();
 		$this->bufferRecv = new QueryRecvQueue();
-		$this->addWorker();
+
+		for($i = 0; $i < $workerLimit; $i++){
+			$this->addWorker();
```
Comment (SOF3) [inline libasynql/src/poggit/libasynql/base/SqlThreadPool.php]: Do we need to maximize the number of workers directly upon startup? What is the problem with lazy worker initialization?

**Review by SOF3 — DISMISSED** [review]

File: libasynql/src/poggit/libasynql/base/QuerySendQueue.php [hunk 4]
```diff
@@ -23,21 +23,48 @@
...
 class QuerySendQueue extends Threaded{
-	public function scheduleQuery(int $queryId, int $mode, string $query, array $params) : void{
-		$this[] = serialize([$queryId, $mode, $query, $params]);
+	/** @var bool */
+	private $invalidated = false;
+	/** @var Threaded */
+	private $queries;
+
+	public function __construct(){
+		$this->queries = new Threaded();
```
Comment (SOF3) [inline libasynql/src/poggit/libasynql/base/QuerySendQueue.php:35]: Is there a particular reason not to use `$this`?

**Comment by SOF3** [comment]
I am not very familiar with the pthreads semantics nor Snooze, so I will let @dktapps decide whether this PR is ok to merge.

File: libasynql/src/poggit/libasynql/base/QuerySendQueue.php (hunk 4 above)
Comment (CortexPE) [reply libasynql/src/poggit/libasynql/base/QuerySendQueue.php:35]: it required an encapsulated threaded queue so that we could shift ***that*** instead of the main one which now has an "invalidate" property... for some unknown reason, shifting a pthreads `Threaded` object shifts its properties too.
